name: “Remove before flight” tags

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check-source:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check source tree
      shell: pwsh
      run: |
        ls -Recurse
        | sls -CaseSensitive (
              [System.Text.ASCIIEncoding]::new().GetString(
                  [System.Text.Encoding]::GetEncoding(20866).GetBytes(
                      "реможе бефоре флигхт").ForEach({$_ -band 0x7F})))
        | Should -Be @()

  check-pull-request:
    runs-on: windows-latest
    steps:
    - name: Check pull request
      shell: pwsh
      run: |
        $event = (Get-Content -Raw $env:GITHUB_EVENT_PATH | ConvertFrom-Json)
        echo $event
        echo $event.after
        $event.head_commit.message
        | Should -Not -MatchExactly (
              [System.Text.ASCIIEncoding]::new().GetString(
                  [System.Text.Encoding]::GetEncoding(20866).GetBytes(
                      "реможе бефоре флигхт").ForEach({$_ -band 0x7F})))
